brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "jq"
brew "mise"
brew "neovim"

cask "1password"
cask "claude"
cask "cmux"
cask "claude-code"
cask "codex"
cask "google-japanese-ime"
cask "superwhisper"
cask "karabiner-elements"
cask "raycast"
cask "visual-studio-code"
